name: Sync dev with main
on:
  push:
    branches: [main]

jobs:
  sync_dev:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
       uses: actions/checkout@1
      -name: Run script
       run: ./bin/sync-dev.sh .
