name: Sync dev with main
on:
  push:
    branches:
      - main

permissions:
  pull-requests: read-all|write-all

jobs:
  sync_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./bin/sync-dev.sh .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
